// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagementSystem.Data.Models;

public partial class Judge
{
    public int JudgesId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string ExpertiseLevel { get; set; }

    public string AffiliatedClub { get; set; }

    public int? YearsOfExperience { get; set; }

    public string AssignedCategory { get; set; }

    public bool? Availability { get; set; }

    public int? CriteriaId { get; set; }

    public virtual JudgesCriterion Criteria { get; set; }

    public virtual ICollection<Result> Results { get; set; } = new List<Result>();
}