// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagementSystem.Data.Models;

public partial class Koi
{
    public int KoiId { get; set; }

    public int? ApplicationId { get; set; }

    public string Name { get; set; }

    public string Species { get; set; }

    public string Breed { get; set; }

    public int? Age { get; set; }

    public DateOnly? Dayofbirth { get; set; }

    public double? Size { get; set; }

    public string ColorPatern { get; set; }

    public string HealthStatus { get; set; }

    public virtual Application Application { get; set; }

    public virtual ICollection<Contest> Contests { get; set; } = new List<Contest>();
}