// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagementSystem.MVCWebApp.Models;

public partial class Application
{
    public int ApplicationId { get; set; }

    public int? KoiId { get; set; }

    public int? ConstestId { get; set; }

    public string Status { get; set; }

    public DateOnly? ReviewDate { get; set; }

    public DateOnly? SubmissionDate { get; set; }

    public string RankAssigned { get; set; }

    public string Note { get; set; }

    public string PaymentStatus { get; set; }

    public int? UserId { get; set; }

    public string ContestSection { get; set; }

    public virtual ICollection<Koi> Kois { get; set; } = new List<Koi>();

    public virtual User User { get; set; }
}