// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagementSystem.MVCWebApp.Models;

public partial class Contest
{
    public int ContestId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Location { get; set; }

    public string Status { get; set; }

    public int? KoiId { get; set; }

    public string ContestType { get; set; }

    public string PrizePool { get; set; }

    public virtual ICollection<JudgesCriterion> JudgesCriteria { get; set; } = new List<JudgesCriterion>();

    public virtual Koi Koi { get; set; }
}