// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiShowManagementSystem.MVCWebApp.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Role { get; set; }

    public string Password { get; set; }

    public DateOnly? Dayofbirth { get; set; }

    public string Address { get; set; }

    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();
}